---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springdeployment
spec:
  replicas: 4
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: springbootimage
  template:
    metadata:
      name: springbootimage
      labels:
        app: springbootimage
    spec:
      containers:
      - name:  springbootcontainer
        image: rjthapaa/springbootimage
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springbootsvc
spec:
  type: NodePort
  selector:
    app: springbootimage
  ports:
    - port: 80
      targetPort: 8080
...
